name: Release preview
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          package-manager-cache: false

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Create release preview PR
        run: pnpm exec pkg-pr-new publish "."
